## Switches
#set_property PACKAGE_PIN W16 [get_ports a]
#        set_property IOSTANDARD LVCMOS33 [get_ports a]
#set_property PACKAGE_PIN V16 [get_ports b]
#        set_property IOSTANDARD LVCMOS33 [get_ports b]
#set_property PACKAGE_PIN V17 [get_ports c]
#        set_property IOSTANDARD LVCMOS33 [get_ports c]
        
## LEDs
#set_property PACKAGE_PIN V14 [get_ports {y[7]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[7]}]
#set_property PACKAGE_PIN U14 [get_ports {y[6]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[6]}]
#set_property PACKAGE_PIN U15 [get_ports {y[5]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[5]}]
#set_property PACKAGE_PIN W18 [get_ports {y[4]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[4]}]
#set_property PACKAGE_PIN V19 [get_ports {y[3]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[3]}]
#set_property PACKAGE_PIN U19 [get_ports {y[2]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[2]}]
#set_property PACKAGE_PIN E19 [get_ports {y[1]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[1]}]
#set_property PACKAGE_PIN U16 [get_ports {y[0]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {y[0]}]

##7 segment display
#set_property PACKAGE_PIN W4 [get_ports {display_out[10]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[10]}]
#set_property PACKAGE_PIN V4 [get_ports {display_out[9]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[9]}]
#set_property PACKAGE_PIN U4 [get_ports {display_out[8]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[8]}]
#set_property PACKAGE_PIN U2 [get_ports {display_out[7]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[7]}]
#set_property PACKAGE_PIN W7 [get_ports {display_out[6]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[6]}]
#set_property PACKAGE_PIN W6 [get_ports {display_out[5]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[5]}]
#set_property PACKAGE_PIN U8 [get_ports {display_out[4]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[4]}]
#set_property PACKAGE_PIN V8 [get_ports {display_out[3]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[3]}]
#set_property PACKAGE_PIN U5 [get_ports {display_out[2]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[1]}]
#set_property PACKAGE_PIN V5 [get_ports {display_out[1]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[2]}]
#set_property PACKAGE_PIN U7 [get_ports {display_out[0]}]
#        set_property IOSTANDARD LVCMOS33 [get_ports {display_out[0]}]